name: aoc2020
version: 0.1.0.0
github: "tupini07/advent-of-code"
license: MIT
author: "Andrea Tupini"
maintainer: "tupini07@gmail.com"
copyright: "2020 Andrea Tupini"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/haskell#readme>

ghc-options:
  - -Wall
  - -fwarn-tabs
  - -fno-warn-type-defaults
dependencies:
  - base >= 4.7 && < 5
  - MissingH
  - QuickCheck
  - array
  - base16-bytestring
  - bytestring
  - containers
  - cryptohash-md5
  - data-has
  - extra
  - filepath
  - hashable
  - lens
  - monad-loops
  - monad-validate
  - mtl
  - parallel
  - parsec
  - pqueue
  - primitive
  - random
  - safe
  - split
  - string-qq
  - tasty
  - tasty-hunit
  - tasty-quickcheck
  - time
  - transformers-base
  - unordered-containers
  - vector

library:
  source-dirs: src

executables:
  aoc2020-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -O2
      - -threaded -rtsopts -with-rtsopts=-N4
      - -fno-warn-missing-signatures
      - -fno-warn-unused-top-binds
      - -fno-warn-unused-do-bind
      - -fno-warn-unused-imports
    dependencies:
      - aoc2020

tests:
  aoc2020-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - aoc2020
